config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
    resources :pins
    
    root "pins#index"
    
  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/pin.rb
class Pin < ActiveRecord::Base
    validates_presence_of :title
    
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    
   has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
    before_action :find_pin, only: [:show, :edit, :update, :destroy]
    
    def index
        @pins = Pin.all.order("created_at DESC")
    
    end
    def show
        
    
    end
    
    def new
        @pin = current_user.pins.build
    end
    
    def create
        @pin = current_user.pins.build(pin_params)
        if @pin.save
            redirect_to @pin, notice: "successfully created new Pin!"
        else
            render 'new'
        end
    end

    def edit
        
    end
    
    def update
        if @pin.update(pin_params) 
            redirect_to @pin, notice: "successfully updated"
        else
            render 'edit'
        end
    end
    
    def destroy
        @pin.destroy
        redirect_to root_path
    end
    
    private
    
    def pin_params
        params.require(:pin).permit(:title, :description)
    end
    
    def find_pin
        @pin = Pin.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
    %head
        %title PinApp
        = stylesheet_link_tag  'application.css', media: 'all', 'data-turbolinks-track' => true 
        = javascript_include_tag 'application.js', 'data-turbolinks-track' => true 
        = csrf_meta_tags
    %body
        %nav.navbar.navbar-default
            .container
                .navbar-brand= link_to "PinApp", root_path

                - if user_signed_in?
                    %ul.nav.navbar-nav.navbar-right
                        %li= link_to "new Pin", new_pin_path 
                        %li= link_to "Account", edit_user_registration_path 
                        %li= link_to "Sign out", destroy_user_session_path, method: :delete
                - else 
                    %ul.nav.navbar-nav.navbar-right
                        %li= link_to "Sign up", new_user_registration_path 
                        %li= link_to "Sign in", new_user_session_path
        .container            
            - flash.each do |name, msg|
                = content_tag :div, msg, class: "alert alert-info"


            = yield 

app/views/pins/_form.html.haml
= simple_form_for @pin, html: { multipart: true } do |f|
    - if @pin.errors.any?
        #errors
            %h2
            = pluralize(@pin.errors.count, "error")
            prevented this Pin from saving
            %ul
                - @pin.errors.full.messages.each do |msg|
                    %li= msg
            
    .form-group
        = f.input :title, input_html: { class: 'form-control'}
        
    .form-group
        = f.input :description, input_html: { class: 'form-control'}
    = f.button :submit, class: "btn btn-primary"
    

app/views/pins/edit.html.haml
.col-md-6.col-md-offset-3
    %h1 Edit Pin

    = render 'form'
    = link_to "Cancel", pin_path

app/views/pins/index.html.haml
- @pins.each do |pin| 
    %h2= link_to pin.title, pin
    %p= pin.description
    

app/views/pins/new.html.haml
.col-md-6.col-md-offset-3

    %h1 new form

    = render 'form'

    = link_to "back", root_path 

app/views/pins/show.html.haml
%h1= @pin.title
%h1= @pin.description

%p 
submitted by
= @pin.user.email

%br/
= link_to "back", root_path
= link_to "edit", edit_pin_path
= link_to "delete", pin_path, method: :delete, data: {confirm: "Are you sure?"}